### ISSUE TITLE
[Patch] Wrong desktop file

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#1]
desktop-file-validate gCAD3D.desktop
gCAD3D.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
gCAD3D.desktop: warning: value "GTK;Application;Graphics;VectorGraphics;Viewer;" for key "Categories" in group "Desktop Entry" contains a deprecated value "Application"
gCAD3D.desktop: hint: value item "VectorGraphics" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Graphics;2DGraphics
gCAD3D.desktop: error: key "GenericName[de]" in group "Desktop Entry" is a localized key, but there is no non-localized key "GenericName"
gCAD3D.desktop: error: key "GenericName[en]" in group "Desktop Entry" is a localized key, but there is no non-localized key "GenericName"

```diff
[Desktop Entry]
Name=gCAD3D
GenericName=CAD-CAM-Application
Comment=3D CAD CAM design tool
Exec=gcad3d
Icon=/usr/share/gcad3d/icons/gCAD3D.xpm
Type=Application
Categories=GTK;Graphics;
Terminal=false


# Translations
GenericName[de]=CAD-CAM-Anwendung
Name[de]=gCAD3D
Icon[de]=/usr/share/gcad3d/icons/gCAD3D.xpm
Comment[ru]=3D САПР
GenericName[ru]=САПР
Name[ru]=gCAD3D
Icon[ru]=/usr/share/gcad3d/icons/gCAD3D.xpm
```
1) Get gCAD3D.desktop from transifex.com from English (it will include all translations)
2) chmod 644 gCAD3D.desktop

**Comment by glixx** [comment]
No, not fixed. Your desktop file is wrong again.

**Comment by gcad3d** [comment]
https://github.com/gcad3d/gcad3d/blob/master/debian/gCAD3D.desktop
is modified; whats wrong ?

**Comment by glixx** [comment]
Should be with this content:
```diff
[Desktop Entry]
Name=gCAD3D
GenericName=CAD-CAM-Application
Comment=3D CAD CAM design tool
Exec=gcad3d
Icon=/usr/share/gcad3d/icons/gCAD3D.xpm
Type=Application
Categories=GTK;Graphics;
Terminal=false


# Translations
GenericName[de]=CAD-CAM-Anwendung
Name[de]=gCAD3D
Icon[de]=/usr/share/gcad3d/icons/gCAD3D.xpm
Comment[ru]=3D САПР
GenericName[ru]=САПР
Name[ru]=gCAD3D
Icon[ru]=/usr/share/gcad3d/icons/gCAD3D.xpm
```
Your desktop file:
Encoding is deprecated, Application for Categories is deprecated, GenericName[en]= should be GenericName=, Exec should be without path, Categories is not OK (see "desktop-file-validate gCAD3D.desktop" output in the first message)

**Comment by gcad3d** [comment]
Fixed. .?

**Comment by glixx** [comment]
Yes, fixed
