### ISSUE TITLE
Program causes undefined operation

### ISSUE THREAD

**Issue by awissu** [gcad3d/gcad3d#10]
Hi!
I bumped into rpmlint warnings when building rpm in OBS:
```
[  251s] I: Program causes undefined operation
[  251s]    (likely same variable used twiceand post/pre incremented in the same expression).
[  251s]    e.g. x = x++; Split it in two operations.
[  251s] W: gcad3d sequence-point ../gr/ut_DL.c:2971
```
Build with flags: -O2 -g -m32 -march=i586 -mtune=i686 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables

**Comment by gcad3d** [comment]
thanks, fixed for new version.
