### ISSUE TITLE
fails to build on debian sid for me

### ISSUE THREAD

**Issue by alexmyczko** [gcad3d/gcad3d#12]
hi

i'm trying to make a debian package, however can you have a look at the build log at
http://sid.ethz.ch/debian/gcad3d/

the logfile is called, gcad3d_0+git20180223-1_i386.build, at the very end, is the commands that fail.
any hints, how to build it without the directories you have on your build computer?

**Comment by gcad3d** [comment]
Hi,
sorry, it seems that this directory is missing:
/var/www/debian/gcad3d/gcad3d-0+git20180223/src/tags/
- it is initially empty and will receive the tag-files from ctags after compile.
Maybe should have been added with git add ../src/tags
You could create it manually with mkdir ? until we add this to github.
The next version has many changes and is very not yet ready.
We do not know if this "git add "../tags" could be done directly on github .. ?

**Comment by alexmyczko** [comment]
Thanks the tip for src/tags directory, made it go further... will report further progress.

**Comment by gcad3d** [comment]
Hi, now Version 2.40 (with really many changes) is online.
Have already prepared a rpm.spec, including the file examples.gz,
 which was missing in the suse-package.
File contains example-models and will be extracted if no config-file exists.
