### ISSUE TITLE
Missing examples.gz

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#18]
There are no examples.gz in packages/

**Comment by glixx** [comment]
examples.gz is mandatory to build package, but pack_examples.sh does not work.
Needs to run pack_examples.sh when building package, but it impossible right now.
So workaround is adding examples.gz directly.

**Comment by gcad3d** [comment]
Script ../init_examples.sh (extract example-models) fixed; include the example-models direct from ../../packages/.
