### ISSUE TITLE
Wrong strings

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#2]
msg_es.txt:
Eliminar MMcaDel Catálogo de standardparts
De carga MMapSta y la aplicación de inicio (script)
=>
MMcaDel Eliminar Catálogo de standardparts
MMapSta De carga y la aplicación de inicio (script)

msg_fr.txt
Vr0 pas de variables définies ..
Pedine *** ERROR: insertposition sélectionnez la courbe active ..
Pede1 *** ERROR: PointEditor est active ..
=>
VR0 pas de variables définies ..
PEDine *** ERROR: insertposition sélectionnez la courbe active ..
PEDe1 *** ERROR: PointEditor est active ..

**Comment by gcad3d** [comment]
Thanks, fixed with 2.29 / 2015-11-13
RF
