### ISSUE TITLE
non-standard-dir-perm

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#26]
gcad3d.x86_64: E: non-standard-dir-perm (Badness: 1) /usr/share/doc/gcad3d/msg 0700
gcad3d.x86_64: E: non-standard-dir-perm (Badness: 1) /usr/share/gcad3d/icons 0700

Fix:
chmod 755 doc/msg
chmod 755 icons

**Comment by gcad3d** [comment]
fixed V-2.42.02
