### ISSUE TITLE
spurious-executable-perm

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#28]
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/ut/cv_parl_pln.c
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/exp/print_pdf.c
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/ut/ut_face.c
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/ut/ut_log.c
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/gr/glbt.c
gcad3d-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/mnt/serv1/Devel/gcad3d/src/xa/xa_print__.c

find ./ -name *.c -exec chmod 644 {} \;

**Comment by gcad3d** [comment]
Thanks - fixed with V-2.42.05
