### ISSUE TITLE
English and German are different

### ISSUE THREAD

**Issue by glixx** [gcad3d/gcad3d#29]
Please fix strings:
"MAN: paste textBuffer after delete or ctrl X"
"Viewer"
"B-Spline = join (connect) lines/circs/b-splines" (Circles or Arcs?)
"select or keyIn obj to dump .."

**Comment by gcad3d** [comment]
In msg_en.txt some lines have more than one "="; eg:
"S_BSpline___convert___join_obj_s=B-Spline = join (connect) lines/circs/b-splines"
- maybe this is a problem for the translation-SW ?
- does the translating SW use all "="-characters 
 or only the first in line ?

**Comment by glixx** [comment]
Everything is ok with "=".

Problem is English original string is different with German. I guess you forgot to update English string or German string is deprecated.

```
MMinTxt=MAN: paste textBuffer after delete or ctrl X
MMinTxt=Ausgabe Textpuffer (nach Entf oder Strg X) / Strg Entf

MMrbVwr=Viewer
MMrbVwr=Viewer (nur Anzeige und Analyse, kein Editieren)

S_BSpline___convert___join_obj_s=B-Spline = join (connect) lines/circs/b-splines
S_BSpline___convert___join_obj_s=B-Spline = Verbindung aus mehrerern Linien/Kreisbögen/B-SplineKurven
```

**Comment by gcad3d** [comment]
Fixed.
