### ISSUE TITLE
Non-standard icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [gcad3d/gcad3d#3]
Currently the icon path in the [application launcher file](https://github.com/gcad3d/gcad3d/blob/30ae136b8a9baa5d4680679dce7377a4fb4298ee/debian/gCAD3D.desktop) is hardcoded to the following non-standard path:
``Icon=/usr/share/gcad3d/icons/gCAD3D.xpm``

This prevents icon theming without editing the launcher file. 

According to the [freedesktop.org standard](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) valid application launcher icon locations are: 
``/usr/share/icons/hicolor/[size]/apps/``
``~/.local/share/icons/hicolor/[size]/apps/``
``/usr/share/pixmaps/``

According to the standard and w.r.t. icon lookup mechanisms of GNU/Linux DEs for an icon installed to a standard location you can change the icon path line to simply: 
``Icon=gCAD3D`` (absolute path and file type extension not needed)

Please find an example ``.desktop`` file [here](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example)

Could you please install the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by gcad3d** [comment]
Ok, we will add:
cp /usr/share/gcad3d/icons/gCAD3D.xpm /usr/share/pixmaps/.
and in gCAD3D.desktop change Icon=/usr/.. into:
Icon=gCAD3D
Would that be ok ?
Franz;

**Comment by palob** [comment]
Yeah, that should do it. Thank you.

**Comment by gcad3d** [comment]
Fixed with (not official) version 2.31.
Franz.
