### ISSUE TITLE
Wrongest info version

### ISSUE THREAD

**Issue by pafurijaz** [gcad3d/gcad3d#36]
Hi and thanks for your works, there is a little mistake on description on Linux version, that report a different version name than released, the header and info say 2.46.10 instead of 2.46.12  the system report the correct version 2.46.12.

**Comment by gcad3d** [comment]
im not very familiar to github - where / which file - should we update the version-nr ?

**Comment by pafurijaz** [comment]
I really don't know where but this is a problem related to the source code, not to github.. these below show what I mean. on the system show the correct version only with on the application there is the wrong label
![Istantanea_2020-05-20_19-19-28](https://user-images.githubusercontent.com/11751383/82476822-dffc0f00-9ace-11ea-8d8c-30dcaf69d836.png)
![Istantanea_2020-05-20_19-12-02](https://user-images.githubusercontent.com/11751383/82476824-e12d3c00-9ace-11ea-882f-6d2530a2bd6e.png)
![Istantanea_2020-05-20_19-10-43](https://user-images.githubusercontent.com/11751383/82476826-e12d3c00-9ace-11ea-95d0-bd44d92874bd.png)
![gCAD3D_v](https://user-images.githubusercontent.com/11751383/82476829-e1c5d280-9ace-11ea-94cc-f7984cd657e5.png)

**Comment by gcad3d** [comment]
problem found. will be fixed.

**Comment by gcad3d** [comment]
issue fixed with V2.46.14.
