### ISSUE TITLE
Version gCAD3D-2.46.22 for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by pafurijaz** [gcad3d/gcad3d#44]
Hi, I have compiled a version for Ubuntu 18.04.6 LTS,  because the new version available for download, it only works with Ubuntu 20.04 LTS.
  I am also attaching the compressed .deb file, it could be useful for those like me who have not yet made the switch to the new operating system.
[gCAD3D-2.46.22-bin-amd64.deb.tar.gz](https://github.com/gcad3d/gcad3d/files/7875533/gCAD3D-2.46.22-bin-amd64.deb.tar.gz)

**Comment by gcad3d** [comment]
Ok to provide deb-binaries not from newest versions -
will release a new V 2.46.24 asap.
