### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by pafurijaz** [gcad3d/gcad3d#45]
Hi I managed to compile the previous version but this new version seems to be fine, but when I try to do the launch with the command ./do it does not find the gCAD3D file.

I don't understand why this happens below the output of the ./do complete command. 
and the error I get when I try to test with ./do.

```
====================== Link plugins/PRC_demo1 ======================
cd /home/pafu/devel/bin/gcad3d/Linux_x86_64/ &&\
gcc -o plugins/PRC_demo1.so  prc_Demo1__.o\
     -shared -export-dynamic
make[1]: uscita dalla directory "/home/pafurijaz/devel/gcad3d/src/APP"
touch ../prc/cut1/G-Code.c
make -f ../prc/cut1/G-Code.mak
make[1]: ingresso nella directory "/home/pafurijaz/devel/gcad3d/src/APP"
build G-Code -> /home/pafu/devel/bin/gcad3d/Linux_x86_64/
cc -o G-Code ../prc/cut1/G-Code.c  ../prc/cut1/pp_ut.c  -lm
ctags --excmd=number -f ut.tag ../prc/cut1/pp_ut.c
mv -f G-Code /home/pafu/devel/bin/gcad3d/Linux_x86_64/plugins/cut1/.
make[1]: uscita dalla directory "/home/pafu/devel/gcad3d/src/APP"
if [ $? -ne 0 ]; then exit 1; fi
link processes done OK
- success do complete
```
```
~/devel/gcad3d/src/APP$ ./do
start - OSTYPE =  Linux
normal start ..
./do: 614: ./do: /home/pafu/devel/bin/gcad3d/Linux_x86_64/gCAD3D: not found

```
Thanks

**Comment by ckitgui** [comment]
building the coremodule failed; do:
./do gui-gkt3 > t1 2>&1
./do c >> t1 2>&1
- this will build the coremodule and write all messages into file t1.
- if not coremodule yet, send us t1 to support at gacd3d.org.

**Comment by pafurijaz** [comment]
Thanks now works well but I've done every step in the documentation to build the application, and there is an other problem related to missing file when I try to execute the command (**./do init_examples**) I have this new errors:

```
~/devel/gcad3d/src/APP$ ./do init_examples
DIR_DEV=|/home/pafurijaz/devel/|
DIR_BIN=|/home/pafurijaz/devel/bin/|
****** ERROR - file packages/examples.gz does not exist. *******

```

This is a screen shot of the new version.
![image](https://user-images.githubusercontent.com/11751383/150185246-dda65a1f-a205-4c34-b8b4-4919861700b4.png)

But now works and I'm able to make the **Debian package** from this new sources, but maybe is without example, for now I will close this report without open a new issue about missing **example.gz**
I trust that you will correct this error as well
I cloned the git repository to do this test.
Greetings
