### ISSUE TITLE
/usr/bin/ld: cannot find xa_gui.so: No such file or directory

### ISSUE THREAD

**Issue by Pavel-Sayekat** [gcad3d/gcad3d#46]
On my Archlinux derivative (Parabola), it is show while I run "./do complete"

cd /home/user/gcad3d/src/APPbin/gcad3d/Linux_x86_64/ && \
cc -o gCAD3D\
  xa.o xa_msg.o mdl__.o xa_obj_txt.o xa_edi__.o xa_ed.o xa_ed_mem.o xa_src.o xa_ato.o xa_grp.o xa_ga.o xa_dll.o xa_app.o xa_appDat.o catalog.o ckint_fac.o cvoff2.o mdlfn.o ut_DB.o ut_dbo.o NC_Main.o NC_apt.o ut3d_npt.o ut2d_npt.o ut_gtypes.o ut_ox_base.o ut_transform.o ut_ui_TX.o ut_pspl.o ut_bspl.o ut_rbspl.o ut_bsp_approx.o cvClot.o utemp.o cirMoeb.o ut_col.o ut_srv.o ut_sru.o ut_dump.o ut_err.o ut_surstd.o ut_sbsp.o ut_srbsp.o ut_objtab.o ut_bez.o ut_rbez.o ut_tria.o ut_quat.o ut_plg.o ut_cvtrm.o ut_elli.o ut_cvApp.o ut_sdc.o ut_project.o ut_gsrc.o ut_tess.o ut_hatch.o ut_log.o ubs.o ubscrv.o ubssur.o sbsu1.o u3d.o ut_cvoff.o ut_msh.o ut_face.o tess_su.o ut_tess_su.o tess_ut.o tess_vr_ut.o ut_GLU.o glbt.o grtsu.o ut_prcv__.o ut_prcv_db.o ut_cntf.o ut_geo2d.o ut_geo3d.o ut_iTab.o ut_dbf.o ut_obj.o ut_txfil.o ut_txt.o ut_umb.o ut_math.o ut_umem.o ut_mem.o ut_box.o ut_txTab.o ut_int.o ut_uti.o byteorder.o ut_memTab.o ut_memTab1.o itab.o ut_BitTab.o deb_prt.o tstf__.o ut_os__.o xa_main.o xa_ctrl.o xa_ui.o xa_cad_ui.o xa_cad_inp.o xa_cad_ccv_ui.o xa_cad_ed1.o xa_sele.o xa_brw.o xa_gmvo.o xa_ted.o xa_meas.o xa_mod_att.o xa_ico.o xa_objmenu.o xa_objvwr.o xa_aux.o xa_undo.o xa_del.o ui_tex.o xa_tex.o xa_ui_gr.o xa_vwpt.o xa_tra.o xa_plu.o xa_prg.o xa_proc.o xa_objLst.o xa_joint.o catalog_gui.o opar.o srcu.o gui_base.o bmp_ut.o csv_ut.o print_pdf.o ds3_r.o ige_w.o prt_w.o lwo_r.o ut_gr.o ut_GL.o ut_DL.o ut_gtx.o gru.o ut_dim.o gr_sSym.o gl_solids.o  os_uix.o ut_os_aix.o ctrl_os_aix.o\
   -lGLU -lGL -lm -ldl  -rdynamic -Wl,--unresolved-symbols=ignore-all\
  xa_gui.so
/usr/bin/ld: cannot find xa_gui.so: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [gcad3d.mak:79: default] Error 1
****** ERROR gcad3d.mak *******
****** ERROR build core *******

**Comment by gcad3d** [comment]
Hallo,
./do gui- should create filexa_gui_gtk2.so   and the linkxa_gui.so ->
xa_gui_gtk2.soin directory Linux_x86_64.
if you have the file Linux_x86_64/xa_gui.so only the link is missing.
Franz

**Comment by Pavel-Sayekat** [comment]
APP ]$ ./do -gui
DIR_DEV=|/home/user/github/gcad3d/src/APP|
DIR_BIN=|/home/user/github/gcad3d/src/APPbin/|
start - OSTYPE =  Linux
LD_LIBRARY_PATH |/home/user/github/gcad3d/src/APPbin/gcad3d/Linux_x86_64/|
gcad_dir_bas    |/home/user/github/gcad3d/src/APPgcad3d/|
gcad_dir_local  |/home/user/github/gcad3d/src/APPgcad3d/|
gcad_dir_ico    |/home/user/github/gcad3d/src/APPgcad3d/icons/|
gcad_dir_doc    |/home/user/github/gcad3d/src/APPgcad3d/doc/|
exeNam          |/home/user/github/gcad3d/src/APPbin/gcad3d/Linux_x86_64/gCAD3D|
****** executable /home/user/github/gcad3d/src/APPbin/gcad3d/Linux_x86_64/gCAD3D does not exist ..

**Comment by ckitgui** [comment]
Hallo,
my last answer was changed by the the transfer Mailprog to github (all CR's removed); sorry.
The command is:
./do gui
WITHOUT hyphen.
See all commands with:
./do help
Franz

**Comment by ckitgui** [comment]
Normally 
./do complete
makes gui.so and creates the linkfile. Will check that ..

**Comment by Pavel-Sayekat** [comment]
Yeah, the issue was reported after running "./do complete" and as it was failing to find xa_gui.so.

**Comment by gcad3d** [comment]
Version 2.60 does not have linked GUI-library; so the problem cannot exist anymore.
