### ISSUE TITLE
MinGW64 testing

### ISSUE THREAD

**Issue by asctime** [gcad3d/gcad3d#47]
```
Neu in Version 1.44 / 2010-02-18...
 MS-Windows: now using MinGW (until now Micosoft Visual-C)

```
Doubtful, as no MinGW targets are clearly defined and WIN32 build chain still uses nmake, after ten years.
"do c", "do gui", etc appear to require complete refactoring to work properly (e.g linking DLL fails because other, as yet unbuilt internal libraries are required, windows only accepts --no-undefined :)

Documentation also still specifies MSVC. Is MinGW dead for this?

**Comment by ckitgui** [comment]
2010 we had one MinGW-version, but since 2011 all versions are using the 32-bit MS VC-compiler of 2010 and nmake.
Building with 64bit VS-community edition 2019 was not successful (could not find the correct runtime-lib for Gtk2 and OpenGL).
Gtk3 has no support for OpenGL-legacy. Gtk4 will provide again support for OpenGL-legacy.
At the moment the implementation of Boolean operations for solids takes great effort, 
so for the next 6 months there will be no time to provide a new toolchain for MS.
Since building works correct on our machines, we can help to fix the problems.
Please provide detailed info of problem.

**Comment by asctime** [comment]
Maybe find the changelog entry where you switched back to MSVC and additionally mention MinGW is no longer supported, from the way I read it could be interpreted that still is. Anyway, interesting about the 64 bit. you should really consider switching back to MSYS2-MinGW64, they have all kinds of 64-bit GTK2, 3 and 4 packages :)

**Comment by gcad3d** [comment]
Many users yet use older Linux systems with Gtk3 so we must use Gtk2 and cannot switch to Gtk4.
Could you help to provide a toolchain for MinGW64 ?

**Comment by asctime** [comment]
Yes.

**Comment by ckitgui** [comment]
If you have some old script or an example could you provide it eg to 
***@***.*** ?

**Comment by asctime** [comment]
The toolchain was overhauled in multiple places but AFAIR I actually just did most of it from within bash, in one casual evening I think. Rather than a couple of paragraphs explaining everything I'm happy to do a PR when I get a free moment. Honestly I wasn't if anyone would be that interested. Please confirm.

**Comment by ckitgui** [comment]
The problem "UTX_setup_get E001" is that the primary setup-files could not be
found.
We will provide a new Version with a MinGW-64-bit version with next gcad-update;
maybe in 2 weeks.

**Comment by asctime** [comment]
BTW I notice that MSYS2-MinGW currently doesn't offer official gtkglarea and gtkglextmm libraries. Did you want to keep that in-house are you looking for someone to push it to the MSYS guys? As long as it's being looked after..

**Comment by ckitgui** [comment]
Msys2 mingw-w64-ucrt-x86_64 (gcc, gdb, gtk2) works fine;
 OpenGL and gtkglarea is missing.
What will be the best package for getting OpenGL32.lib Glu32.lib and
includefiles gl/GL.h und gl/GLU.h ?
Mesa ?
Can we copy gtkglarea from old (MSVC-) installations or where can i get it ?
cscope also is not available; is there a way to get if from another repository ?

**Comment by asctime** [comment]
Don't use mesa. Mingw uses windows native opengl api - link using -lglu32 -lopengl32

I can try to push an official gtkglarea package and see if there is any interest on their side.
Please let me know.

**Comment by ckitgui** [comment]
2 more questions:

MingW64: fatal error: wordexp.h: No such file or directory
- function wordexp does expand shell-varables in char-strings;
  could be replaced by MS-function ExpandEnvironmentStrings;
  but: undefined reference to `ExpandEnvironmentStrings'
- how can this MS-function be linked ?
 
#include <math.h> 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
  int main(int argc, char* argv[])  {    
  int    ii;
  char   s1[256], fn[256];
  strcpy(fn,  "Test %TMP%\\xyz");
  ii = ExpandEnvironmentStrings (s1, fn, 256);
  printf(" ex-OS_osVar_eval %d |%s|%s|\n",ii,s1,fn);
  return 0;
}

..................
Further:
/ucrt64/bin/ctags produces "Segmentation fault" for all sources.
Exuberant Ctags 5.8  Compiled: Apr  2 2021, 12:33:38
Which replacement could be used ?

**Comment by asctime** [comment]
About ExpandEnvironmentStrings, things changed when WinAPI went unicode.
You now have a choice between EnvironmentStringsA and EnvironmentStringsW (wide-character, aka unicode) but you have to let libkernel32 know which one you want. So this, for example, would work:

#include <math.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
  int main(int argc, char* argv[])  {
  int    ii;
  char   s1[256], fn[256];
  strcpy(fn,  "Test %TMP%\\xyz");
  ii = ExpandEnvironmentStringsW (s1, fn, 256);
  printf(" ex-OS_osVar_eval %d |%s|%s|\n",ii,s1,fn);
  return 0;
}

gcc ExpandEnvironmentStrings-test.c -lkernel32 -o ExpandEnvironmentStrings-test.exe
...


About ctags, I see you are using the latest and greatest ucrt64 build. That's cool but keep in mind it's a fairly new version of MinGW and a lot of things might crash unexpectedly. I rolled my own from their github (see above) using an older MinGW64 gcc version and I have no issues, ctags runs fine.

**Comment by asctime** [comment]
@ckitgui are you able to do a gtkglarea PR to the MSYS2 guys or did you want me to? Someone maybe should, in case someone else wants to build gcad windows from source.

**Comment by ckitgui** [comment]
State of porting gcad3d to msys2 / mingw-w64-ucrt-x86_64 is:
most sources have been compiled, but stopped with the following problems:
- cannot get access to OpenGL from Gtk2 - cannot activate gktglarea;
- cannot replace wordexp (wordexp.h) with MS-function ExpandEnvironmentStrings

Minor problems (development only) are:
vim, cscope missing, ctags KO.

Would be great if you could submit this problem to the MSYS2 guys. Thanks.

**Comment by asctime** [comment]
Did you read my [previous post](https://github.com/gcad3d/gcad3d/issues/47#issuecomment-1403480231)? I already showed you how to fix your problem with ExpandEnvironmentStrings .. two different ways .. 

For gtkglarea I have already [prepared a commit](https://github.com/asctime/MINGW-2023-01-13/commit/9c13230624be797fb83412556f20f5ff145d0361) for PR to MSYS2 on your behalf. Please test it.

Please review these contributions and comment.

**Comment by ckitgui** [comment]
Thanks for the info -lkernel32 (that this lib is MS-Stuff).
Sorry that we do not know how to test your gtkglarea-commit.
Can you provide a short howto build and install it ?

**Comment by asctime** [comment]
Sure. Try this (on local pc):

To proceed, understand MSYS2/MinGW64 is TWO toolchains: MSYS2(from CYGWIN) and MinGW64(gcc for native wWndows). This is because some tools, like bash.exe still require posix compatibility and will not compile in a native Windows environment.



1. make sure your MinGW64 and MSYS2 binaries are both in PATH. For me this looks like:
`set PATH=X:\MSYS2\mingw64\bin;X:\MSYS2\mingw64\libexec;X:\MSYS2\mingw64\x86_64-w64-mingw32\bin;X:\MSYS2\usr\bin`
NOTE MinGW GOES IN FRONT (same way it did with the old mingw32)
I have heard the folders will be a little different is you are using ucrt64. You have too look.
2. git clone https://github.com/asctime/MINGW-2023-01-13.git
3. cd MINGW-2023-01-13\mingw-w64-gtkglarea
4. bash -> inside bash run: `MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck`
5. If everything in your environment is ok, it should build a binary package like ""
6. pacman -U mingw-w64-x86_64-gtkglarea-2.1.0-1-any.pkg.tar.xz

**Comment by asctime** [comment]
@gcad3d this discussion has obviously more significance than simple documentation at this point. Permission to simply rename topic as "MinGW64 migration"?

**Comment by ckitgui** [comment]
ad Rename the discussion:   Sure - please do it;
maybe we should use email support at gcad3d for minor important issues ..
----------------
ad git clone:
pacman -S mingw-w64-ucrt-x86_64-git-repo
pacman -S mingw-w64-ucrt-x86_64-gitg
$ git clone https://github.com/asctime/MINGW-2023-01-13.git
-bash: git: command not found
- what can be done ? go back to older version ?
----------------
ad et PATH=X:\MSYS2\mingw64\bin;....
where and how should this path be set ? without the windows directories .. ?
----------------
- got a file starting with char '-'; eg like from: echo "test" > -abc
- msys cannot get rid of file "-abc"; (ls -latr *abc* fails)
- could remove it from windows.
Thanks for your help.

**Comment by asctime** [comment]
> ad Rename the discussion: Sure - please do it

Done

> ad git clone: pacman -S mingw-w64-ucrt-x86_64-git-repo pacman -S mingw-w64-ucrt-x86_64-gitg $ git clone https://github.com/asctime/MINGW-2023-01-13.git -bash: git: command not found

These are all incorrect, unfortunately. You downloaded [Gitg](https://wiki.gnome.org/Apps/Gitg/) - a GUI wrapper for git.
There is no current MinGW version of git - you need to install the MSYS version:
`pacman -S git`
It should work.

> where and how should this path be set

I am confused. Do you mean, "how to change your system path in Windows"?
or "What should I set it to?"

The first question is [basic Windows](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/) information.

I don't know where you installed MinGW -> there are at least three folders to add:
Front: Your MinGW 'bin' 
Middle: Your MinGW platform bin where the 'ld.exe' is located (for me this is mingw64\x86_64-w64-mingw32\bin)
Last: Your MSYS 'usr/bin'

You have to look on your own system, find these folders and add them to the system path.

**Comment by asctime** [comment]
Your running git in MINTTY or bash and ":" is a reserved character on the
POSIX command line.

Run the command in a normal command prompt (not MINTTY or bash)

It's worth noting that bash on WIndows is a bit of a kludge, and has had
all kinds of nuances and issues. Only use it when you HAVE to (like running
shell scripts like "makepkg-mingw" or autotools that REQUIRE the shell they
are scripted in).

Otherwise do everything in plain CMD. Avoid MINTTY completely.

**Comment by asctime** [comment]
Also try the same command without the ".git" at the end, eg:
git clone https://github.com/asctime/MINGW-2023-01-13

Seems to make a difference for some users
(either way works for me)

So basically you should always be working in a vanilla command prompt, except for step number 4. If your PATH is correct you can switch in-and-out of bash at any time like so:

```
X:\>cd MINGW-2023-01-13
X:\TMP>bash

foo@bar  /x/MINGW-2023-01-13
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck
$ exit
exit

D:\TMP>
```

**Comment by asctime** [comment]
Sorry I forgot the subdir name (edited in post):

```
X:\>cd MINGW-2023-01-13\mingw-w64-gtkglarea
X:\TMP>bash

foo@bar  /x/MINGW-2023-01-13/mingw-w64-gtkglarea
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck
$ exit
exit

X:\TMP>
```

**Comment by ckitgui** [comment]
clone successful,
but PKGBUILD missing. ???
--------------------------------------------------
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck
=> WARNING: MINGW_INSTALLS is deprecated, use MINGW_ARCH instead
==>  MINGW_ARCH: mingw64
  -> Building mingw64...
==> FEHLER: PKGBUILD existiert nicht.

**Comment by asctime** [comment]
I just did a test clone and it is definitely there. What directory are you in when you run makepkg-mingw?

Are you actually running it inside the "mingw-w64-gtkglarea" sub-folder like posted?

**Comment by asctime** [comment]
https://packages.msys2.org/package/mingw-w64-x86_64-binutils

Also, as I already said, make sure that **msys64\ucrt64\bin** and **msys64\ucrt64\x86_64-w64-mingw32\bin** is at the **FRONT** (e.g. first in line) of your **PATH**. In case you might have a different version of 'strip' from another distribution.

**Comment by gcad3d** [comment]
-------------------------------------------------
find strip.exe:
C:\msys64\ucrt64\bin\strip.exe
C:\msys64\ucrt64\x86_64-w64-mingw32\bin\strip.exe

-------------------------------------------------
set PATH=C:\msys64\ucrt64/bin;C:\msys64\ucrt64\libexec;C:\msys64\ucrt64\x86_64-
w64-mingw32\bin;C:\msys64\usr\bin;%PATH%

echo %PATH%

C:\msys64\ucrt64/bin;C:\msys64\ucrt64\libexec;C:\msys64\ucrt64\x86_64-w64-
mingw32\bin;C:\m
sys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows
\System32\
WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
Files\dotnet\;C:\Program F
iles\Microsoft SQL Server\110\Tools\Binn\;C:\Users\Franz
Reiter\AppData\Local\Microsoft\Wi
ndowsApps;C:\Users\Franz Reiter\.dotnet\tools;

which strip.exe
/ucrt64/bin/strip.exe

cd C:\Users\Franz Reiter\MINGW-2023-01-13\mingw-w64-gtkglarea

which bash
/usr/bin/bash

bash

$ echo $PATH

/ucrt64/bin:/ucrt64/libexec:/ucrt64/x86_64-w64-
mingw32/bin:/usr/bin:/c/Windows/system32:/c/Windows:/c/W
indows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/Syste
m32/OpenSSH:/c/Program
Files/dotnet:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Users/Franz
Reiter/AppData/Local/M
icrosoft/WindowsApps:/c/Users/Franz Reiter/.dotnet/tools

$ MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck
=> WARNING: MINGW_INSTALLS is deprecated, use MINGW_ARCH instead
==>  MINGW_ARCH: mingw64
  -> Building mingw64...
==> FEHLER: Cannot find the strip binary required for object file stripping.

$ which strip
/ucrt64/bin/strip

$ exit

-------------------------------------------------
# changed order:
set PATH=C:\msys64\ucrt64\x86_64-w64-
mingw32\bin;C:\msys64\ucrt64/bin;C:\msys64\ucrt64\libexec;C:\msys64\usr\bin;%PAT
H%
..
==> FEHLER: PKGBUILD existiert nicht.

**Comment by asctime** [comment]
> ------------------------------------------------- # changed order: set PATH=C:\msys64\ucrt64\x86_64-w64- mingw32\bin;C:\msys64\ucrt64/bin;C:\msys64\ucrt64\libexec;C:\msys64\usr\bin;%PAT H% .. ==> FEHLER: PKGBUILD existiert nicht.


That has nothing to do with PATH.

It means you have wrong CWD again. Remember, BASH and CMD are different environments, so CWD in one does not always mean CWD in the other. 

Always check everything with simple 'ls' if you aren't sure.

**Comment by asctime** [comment]
Also this is very wrong:

PATH=C:\msys64\ucrt64\x86_64-w64- mingw32\bin;**C:\msys64\ucrt64/bin;**


You used UNIX slash to define a WINDOWS path  - should be:
PATH=**C:\msys64\ucrt64\bin;C:\msys64\ucrt64\x86_64-w64- mingw32\bin;...

**Comment by asctime** [comment]
Please also review my comments on github itself as the may be edited and email will not reflect this.

**Comment by gcad3d** [comment]
repairing the wrong slash does not help; exactly same problem.
What do you mean with "It means you have wrong CWD again." - whats CWD ?
What could be checked with "check everything with simple 'ls'" ?
I think PKGBUILD changes the path and cannot get one of the 2 strip.exe's.

**Comment by asctime** [comment]
These are just tools to help you make sure you are actually working in the correct folder:
https://en.wikipedia.org/wiki/Working_directory = the folder you are currently working in (use the 'pwd' command to check)

https://en.wikipedia.org/wiki/Ls = list the contents of current folder

I pushed an update to remove the strip option from PKGBUILD completely. Maybe it creates some weird issue, so let's try to move things along. Otherwise you have some kind of system mis-configuration that goes beyond this discussion.

Please delete your existing MINGW-2023-01-13 folder and re-clone everything and [start again from the beginning](https://github.com/gcad3d/gcad3d/issues/47#issuecomment-1405109513).

**Comment by gcad3d** [comment]
2023-02-01 MEZ-09:00: did rmdir/S MINGW-2023-01-13 and .git, clone and install,
exactly the same: Cannot find the strip binary ..

find strip.exe gives:
C:\msys64\ucrt64\bin\strip.exe
C:\msys64\ucrt64\x86_64-w64-mingw32\bin\strip.exe
??

**Comment by asctime** [comment]
> 2023-02-01 MEZ-09:00: did rmdir/S MINGW-2023-01-13 and .git, clone and install, exactly the same: Cannot find the strip binary .. find strip.exe gives: C:\msys64\ucrt64\bin\strip.exe C:\msys64\ucrt64\x86_64-w64-mingw32\bin\strip.exe ??

Strange that this is only an issue finding strip -> not gcc or perl etc
Please look inside the folder like mingw-w64-gtkglarea\src\build-ucrt_64-w64-mingw32\gtkgl
You will find a generated file called **Makefile**
Look at line approx 228. Mine looks like this:
```

PACKAGE_VERSION = 2.1.0
PATH_SEPARATOR = :
PKG_CONFIG = /mingw64/bin/x86_64-w64-mingw32-pkg-config
PKG_CONFIG_LIBDIR =
PKG_CONFIG_PATH = /mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE =
SHELL = /bin/sh
STRIP = strip
VERSION = 2.1.0
```

Now look at the folder above, like, mingw-w64-gtkglarea\src\build-ucrt_64-w64-mingw32
You will find a generated file called "libtool"

Look at line approx 156. Mine looks like this:
```
# Flags to create an archive.
AR_FLAGS="cru"

# How to feed a file listing to the archiver.
archiver_list_spec="@"

# A symbol stripping program.
STRIP="strip"

# Commands used to install an old-style archive.
RANLIB="ranlib"
old_postinstall_cmds="chmod 644 \$oldlib~\$RANLIB \$tool_oldlib"
old_postuninstall_cmds=""
```


I seem to recall beyond-stupid template values for these when I installed MSYS2.
Please check some pseudo-cygwin gibberish isn't defined here like  
`STRIP="/cygdrive/usr/bin/strip"`
or some silliness.


Please check these two files and post what you discover.

**Comment by asctime** [comment]
Actually if MSYS2 automake has broken STRIP settings you might not even be getting that far.

Let's try something simple and see if it fixes the problem.
Please look inside the folder like mingw-w64-gtkglarea
You will find a file called "PKGBUILD"

Edit line 30 to look like this:
`STRIP=strip AR=ar ./configure \`

Then re-run `MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck`

It's a massive shot in the dark, but worth a try.

**Comment by asctime** [comment]
Actually, check that. Lets go with this instead at line 30, in case MSYS2 guys say I'm breaking parallel builds. Also you might have the same issue with RANLIB anyway. mingw-w64-gtkglarea\PKGBUILD, Line 30. Please substitute

`./configure \`

with

```
STRIP=${MINGW_PREFIX}/bin/strip.exe AR=${MINGW_PREFIX}/bin/ar.exe \
RANLIB=${MINGW_PREFIX}/bin/ranlib.exe ./configure \
```

**Comment by gcad3d** [comment]
the content of my directory
C:\Users\Franz Reiter\MINGW-2023-01-13\mingw-w64-gtkglarea   is:

01.02.2023  08:48               752 001-mingw-autotools.patch
01.02.2023  08:48             1 477 PKGBUILD

- nothing else !

Have changed in PKGBUILD to:

#  ./configure \
  STRIP=${MINGW_PREFIX}/bin/strip.exe AR=${MINGW_PREFIX}/bin/ar.exe \
  RANLIB=${MINGW_PREFIX}/bin/ranlib.exe ./configure \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
   --with-lib-opengl32


Same result: Cannot find the strip binary ..

**Comment by asctime** [comment]
> the content of my directory C:\Users\Franz Reiter\MINGW-2023-01-13\mingw-w64-gtkglarea is: 01.02.2023 08:48 752 001-mingw-autotools.patch 01.02.2023 08:48 1 477 PKGBUILD - nothing else ! 

This is right. Good.

> Have changed in PKGBUILD to: # ./configure \ STRIP=${MINGW_PREFIX}/bin/strip.exe AR=${MINGW_PREFIX}/bin/ar.exe \ RANLIB=${MINGW_PREFIX}/bin/ranlib.exe ./configure \ --prefix=${MINGW_PREFIX} \ --build=${MINGW_CHOST} \ --host=${MINGW_CHOST} \ --with-lib-opengl32 Same result: Cannot find the strip binary ..

This is wrong. Please re-read that post and find what you did incorrectly, then try again.

**Comment by gcad3d** [comment]
have removed line "# ./configure \" - same result.
- is there a debug-mode for PKGBUILD ?
- like -p for make; how could ${MINGW_PREFIX} be checked ?
I have no folder *gtkglarea\src\* in my system;
- when should the download of the
sources occur ?

**Comment by asctime** [comment]
> have removed line "# ./configure \" - same result. - is there a debug-mode for PKGBUILD ? - like -p for make; how could ${MINGW_PREFIX} be checked ? 

msys\usr\bin\makepkg is just a shell script called by makepkg-mingw next to it.
Inside this file you will find the command giving you trouble:
`check_software()`
... about line 1050 or so..
```
if check_option "strip" "y"; then
  if ! type -p strip >/dev/null; then
```

However if _find_ can locate your strip.exe, _type -p strip_ should too.
You could try it once directly in bash and see what you get (this is a bash command).

> I have no folder *gtkglarea\src\* in my system; - when should the download of the sources occur ?

Let's see if updating PKGCONFIG through github works for you instead.
Just run cmd like usual, 'cd' to the repo TOP folder e.g. **X:\MINGW-2023-01-13** ,like usual.
Inside that top folder try to just run:
`git pull`

It _should_ update my mingw-w64-gtkglarea/PKGCONFIG _for_ you. Then try:
```
cd mingw-w64-gtkglarea
bash
(inside bash prompt..)
MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf --skippgpcheck
```


I am not sure what else to try.

**Comment by asctime** [comment]
I was doing some reading last night it looks like there are very recent changes that affect ucrt64 - which you appear to be using. I warned about using latest and greatest!

If my previous post didn't work try this bash command instead:
`MINGW_ARCH=ucrt64 makepkg-mingw -sCLf --skippgpcheck`

**Comment by asctime** [comment]
The problem isn't that your user name has spaces in it, no so far.

The problem is that that's where you actually decided to clone the repo.
So you burden every UNIX shell command the extra task of understanding what that space means. It will never end well.

Put it somewhere else.

**Comment by asctime** [comment]
[#15443](https://github.com/msys2/MINGW-packages/pull/15443) pending review. When/if accepted you will be able to d/l the gtkglarea MinGW library directly from MSYS2 and continue work.

Package fine with their cloud build and all checks pass. I don't expect further issues.
Let me know if you need anything else.

**Comment by gcad3d** [comment]
cd C:\Users\Public
mkdir mswin64
cd mswin64
git init

git clone https://github.com/asctime/MINGW-2023-01-13.git
cd MINGW-2023-01-13
cd mingw-w64-gtkglarea
bash
MINGW_ARCH=ucrt64 makepkg-mingw -sCLf --skippgpcheck
..
==> Säubere Installation...
  -> Entferne libtool Dateien...
  -> Bereinige ungewollte Dateien...
  -> Entferne unnötige Symbole aus Binär-Dateien und Bibliotheken...
  -> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "mingw-w64-ucrt-x86_64-gtkglarea"...
  -> Erstelle .PKGINFO Datei...
  -> Erstelle .BUILDINFO Datei...
  -> Erstelle .MTREE-Datei...
  -> Komprimiere Paket...
==> Beendete Erstellung: mingw-w64-gtkglarea 2.1.0-1 (Do,  2. Feb 2023 14:45:30)

$ pacman -U gtkglarea-2.1.0.tar.xz
loading packages...
error: missing package metadata in gtkglarea-2.1.0.tar.xz
error: 'gtkglarea-2.1.0.tar.xz': invalid or corrupted package

- src\build-x86_64-w64-mingw32\examples\*.exe seem to work correct in this
directory.

**Comment by asctime** [comment]
@gcad3d I am trying to get the binary approved for you so that you can download it directly.

**Comment by asctime** [comment]
I am trying to get this released so that cloud-build can do the packaging
and installation for you with just pacman -S ..

*Can you please visit the ticket ASAP and state your case for this package
and why you still need GTK2.*

<goog_1896051634>
*https://github.com/msys2/MINGW-packages/pull/15443
<https://github.com/msys2/MINGW-packages/pull/15443>*

They don't like it but the truth is they still need and use GTK2 a lot!
You just have to explain the situation yourself since you are the
developer, I think it is better.
I have done my part for you as best that I can, but now this involves more
politics than professional skill :D

**Comment by asctime** [comment]
The package has been approved and the binary for glarea should now be installable via pacman without further needing to build from source.

Ping me if you need anything else.

**Comment by asctime** [comment]
https://packages.msys2.org/package/mingw-w64-x86_64-nsis :)
