### ISSUE TITLE
Building for MInGW missing do?

### ISSUE THREAD

**Issue by asctime** [gcad3d/gcad3d#50]
The local "./do" script referred to in install_en.txt does not exist in repo, no instructions to generate?

Also, this is a standard shell command as well - very confusing.

**Comment by gcad3d** [comment]
Sorry for this; files in src/UIX were missing; have updated.
Unix- and MS-version should build complete with:
./do complete

**Comment by asctime** [comment]
OK I am a little further along but still apparently missing essential build files?

```
DEB = OFF
VGUI = gtk2
- exit devbase.sh

entering build__ complete -------------------------------------------------
- copy systemfiles -
****** ERROR inputfile MSYSFiles.lst does not exist *******
```

This seems to be something pre-packaged, osAux.sh only uses it does not generate it?

```
   # copy files
   ./osAux $1 
```

**Comment by gcad3d** [comment]
MSYSFiles.lst is a list of system-libs used for a binary-package without msys2-
installation. Was remove by a .gitignore - sorry for that. Added.
