### ISSUE TITLE
Crash, with any OBJ file.

### ISSUE THREAD

**Issue by pafurijaz** [gcad3d/gcad3d#52]
Hi, as soon as I select the imported OBJ format model in the 3D view, the program closes immediately. The gCAD3D version used is the latest 2.60.06., that happen with any obj.
[untitled.zip](https://github.com/user-attachments/files/16040861/untitled.zip)

Greetings

**Comment by gcad3d** [comment]
hi,
could import untitled.obj, viewing with no problems, and export it to dxf and
load the dxf OK, using ubuntu 22 and ubu 20; executable was built on ubuntu 18.
Do other models view OK ? What os do you use and which grafic card ?
Greetings

**Comment by pafurijaz** [comment]
The step are these:
Open the and all is OK but when I click on it in the view port to select it gCAD crashed.

this is what I get from output in the console:

```
 ex-AP_impTyp_get 1
AP_kex_exec |xa_obj_r|gCad_main| mode=16
 DLL_LOAD_only |/usr/lib/gcad3d/Linux_x86_64//xa_obj_r.so|
 DLL_CONNECT  |gCad_main|
gCad_main-xa_obj_ut.c
ex-plugin-obj-imp 0
 ex-AP_kex_exec 0
*** stack smashing detected ***: terminated
Aborted (core dumped)

```

And this is the consloe output when I start gcad3d

```
+++++++++++++ Start  gCAD3D Version 2.60.06 2024/06/29-20:31:47
arg[0]|/usr/lib/gcad3d/Linux_x86_64//gCAD3D|
size int:4 long:8 ptr:8
Linux64
Linux sroot-Legion-5-15ACH6H 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Linux version 6.5.0-41-generic (buildd@lcy02-amd64-120) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2
GNU_LIBC_VERSION = |glibc 2.35|
GTK_MAJOR_VERSION=2 GTK_MINOR_VERSION=24
 ex-OS_bin_dir_set |/usr/lib/gcad3d/Linux_x86_64//|
AP_get_dir__ 
- AP_bas_dir = /usr/share/gcad3d/
- AP_loc_dir = /home/sroot/gCAD3D/
- AP_tmp_dir = /home/sroot/gCAD3D/tmp/
- AP_cfg_dir = /home/sroot/gCAD3D/cfg_Linux/
- AP_doc_dir = /usr/share/gcad3d/doc/
- AP_ico_dir = /usr/share/gcad3d/icons/
 lng[0] de
 lng[1] es
 lng[2] ms
 lng[3] en
 lng[4] fr
 lng[5] it
Debug-switch DDEB is ON
 test configfile |/home/sroot/gCAD3D/cfg_Linux/gCAD3D.rc|
 L_startup_defaults:
OS_get_scrRes 3840 1080
AP_defaults_read |/home/sroot/gCAD3D/cfg_Linux/xa.rc|
 AP_mod_dir=|/home/sroot/Documenti/CAD/iges/|
 AP_lang=|it|
 OS_browser=|firefox|
 AP_printer=|lpr -l -PStylus-DX7000F|
 AP_dir_prg=|/home/sroot/gCAD3D/prg/|
 active application=|| 4
 AP_editor=|//|
 AP_winSiz=|-1920,-1034|
 DefaultModelsize=500.000000
AP_defaults_read-AP_winPos |-5,-5|
 AP_winPos=|-5,-5|
MSG_const_init |it|
OMN_init 
AP_DllLst_write 
PRC_lst_processors 
::::DL_alloc__ 10000 320000
GUI_Init__ ||
 f-gtk_init
GTK_MAJOR_VERSION=2 GTK_MINOR_VERSION=24
Ico_init 
 GUI_Ico_init-icoNr=20
UI_fontsizX/Y=6,18
 lang-activate |it|
UI_lang_chg |de|it| 0
UI_lang_chg |it|it| 0
MSG_const_init |it|
 men_hlp-L31
UI_Set_typPrg 4
GL_RENDERER:    (null)
GL_VERSION:     (null)
GL_EXTENSIONS:  (null)
GLU_VERSION:    1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GUI_msgwin__ |e,e|
 win_resize-|-1920,-1034| 1920 1034
OS_dev_ck 
OS_dev_ck 1
MSG_const_init |it|
 ex-GUI_get_version gtk 2 24
::::UTF_alloc__ 100 0 0
 reall > 2000004
ex-UTF_alloc__ 
GL_Init__ mode=0 1715 786
GL_InitInfo
GL_RENDERER:    RENOIR (renoir, LLVM 15.0.7, DRM 3.54, 6.5.0-41-generic)
GL_VERSION:     4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
GLU_VERSION:    1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
 GL_DEPTH_BITS = 24
 GL_STENCIL_BITS = 0
 GL_ACCUM_RED/GREEN/BLUE/ALPHA_BITS = 0 0 0 0
 GL_RED/GREEN/BLUE/ALPHA_BITS = 8 8 8 0
 AP_stat.texture=1
 GL_Init0
::::GLT_alloc_pta 3 0 25000 25000
::::GLT_alloc_cta 1 0 10000 10000
::::GLT_alloc_ppa 1 0 6000 6000
::::GLU_alloc 1 0 400 400
::::DB_allocModRef 0 0 200 200
UI_PRI_unl AP_stat.fVwr = 0
::::DB_allocCDAT 0 2000000
::::DB_allocLine 0 0 5000 5000
GL_selTab_init 0
Brw_init__ 1
AP_tmr_init ............ 
UI_VWR_ON 0
::::UTF_alloc__ 426 2000000 0
 init pipes ..
```

My OS is Ubuntu 22.04 LTS
With NVIDIA GTX 3070

Greetings

**Comment by gcad3d** [comment]
Hi,
- your config:
GL_RENDERER:  RENOIR (renoir, LLVM 15.0.7, DRM 3.54, 6.5.0-41-generic)
> NVIDIA GTX 3070

- tested on Ubuntu 22.04 with
GL_RENDERER:    NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
GL_VERSION:     4.6.0 NVIDIA 535.171.04
- works OK.

- could you try the NV-Renderer ?
Greetings

**Comment by pafurijaz** [comment]
Hi, is the same. 

```
+++++++++++++ Start  gCAD3D Version 2.60.06 2024/06/30-11:47:12
arg[0]|/usr/lib/gcad3d/Linux_x86_64//gCAD3D|
size int:4 long:8 ptr:8
Linux64
Linux sroot-Legion-5-15ACH6H 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Linux version 6.5.0-41-generic (buildd@lcy02-amd64-120) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2
GNU_LIBC_VERSION = |glibc 2.35|
GTK_MAJOR_VERSION=2 GTK_MINOR_VERSION=24
 ex-OS_bin_dir_set |/usr/lib/gcad3d/Linux_x86_64//|
AP_get_dir__ 
- AP_bas_dir = /usr/share/gcad3d/
- AP_loc_dir = /home/sroot/gCAD3D/
- AP_tmp_dir = /home/sroot/gCAD3D/tmp/
- AP_cfg_dir = /home/sroot/gCAD3D/cfg_Linux/
- AP_doc_dir = /usr/share/gcad3d/doc/
- AP_ico_dir = /usr/share/gcad3d/icons/
 lng[0] de
 lng[1] es
 lng[2] ms
 lng[3] en
 lng[4] fr
 lng[5] it
Debug-switch DDEB is ON
 test configfile |/home/sroot/gCAD3D/cfg_Linux/gCAD3D.rc|
 L_startup_defaults:
OS_get_scrRes 1920 1080
AP_defaults_read |/home/sroot/gCAD3D/cfg_Linux/xa.rc|
 AP_mod_dir=|/home/sroot/Documenti/blend_files/Sample/Betty_B/Cilindro_batterie/|
 AP_lang=|it|
 OS_browser=|firefox|
 AP_printer=|lpr -l -PStylus-DX7000F|
 AP_dir_prg=|/home/sroot/gCAD3D/prg/|
 active application=|| 4
 AP_editor=|//|
 AP_winSiz=|-1920,-1034|
 DefaultModelsize=500.000000
AP_defaults_read-AP_winPos |-5,-5|
 AP_winPos=|-5,-5|
MSG_const_init |it|
OMN_init 
AP_DllLst_write 
PRC_lst_processors 
::::DL_alloc__ 10000 320000
GUI_Init__ ||
 f-gtk_init
GTK_MAJOR_VERSION=2 GTK_MINOR_VERSION=24
Ico_init 
 GUI_Ico_init-icoNr=20
UI_fontsizX/Y=6,18
 lang-activate |it|
UI_lang_chg |de|it| 0
UI_lang_chg |it|it| 0
MSG_const_init |it|
 men_hlp-L31
UI_Set_typPrg 4
GL_RENDERER:    (null)
GL_VERSION:     (null)
GL_EXTENSIONS:  (null)
GLU_VERSION:    1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GUI_msgwin__ |e,e|
 win_resize-|-1920,-1034| 1920 1034
OS_dev_ck 
OS_dev_ck 1
MSG_const_init |it|
 ex-GUI_get_version gtk 2 24
::::UTF_alloc__ 100 0 0
 reall > 2000004
ex-UTF_alloc__ 
GL_Init__ mode=0 1715 786
GL_InitInfo
GL_RENDERER:    NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
GL_VERSION:     4.6.0 NVIDIA 535.183.01
GLU_VERSION:    1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
 GL_DEPTH_BITS = 24
 GL_STENCIL_BITS = 8
 GL_ACCUM_RED/GREEN/BLUE/ALPHA_BITS = 16 16 16 16
 GL_RED/GREEN/BLUE/ALPHA_BITS = 8 8 8 0
 AP_stat.texture=1
 GL_Init0
::::GLT_alloc_pta 3 0 25000 25000
::::GLT_alloc_cta 1 0 10000 10000
::::GLT_alloc_ppa 1 0 6000 6000
::::GLU_alloc 1 0 400 400
::::DB_allocModRef 0 0 200 200
UI_PRI_unl AP_stat.fVwr = 0
::::DB_allocCDAT 0 2000000
::::DB_allocLine 0 0 5000 5000
GL_selTab_init 0
Brw_init__ 1
AP_tmr_init ............ 
UI_VWR_ON 0
::::UTF_alloc__ 426 2000000 0
 init pipes ..
UI_men__ |open|
UI_file_open__ |/home/sroot/Documenti/blend_files/clienti/Betty_Buoy/Cilindro_batterie/|
OS_exe_file__ |GUI_file|
OS_exe_file_fn |GUI_file|
 ex-GUI_get_version gtk 2 24
 ex-OS_exe_file_fn |/usr/lib/gcad3d/Linux_x86_64//GUI_file_gtk2|
 ex-GUI_file_in |/tmp/temp_1804289383_in|
***** start exe GUI_file V2.0 2
 ex-OS_bin_dir_set |/usr/lib/gcad3d/Linux_x86_64//|
 ex-GUI_file_out_in |/tmp/temp_1804289383_out|
 ex-GUI_file_out_in |/tmp/temp_1804289383_out|
UI_PRI_unl AP_stat.fVwr = 0
GL_selTab_init 0
Brw_init__ 2
AP_Mod_load_init |/home/sroot/Documenti/blend_files/export/untitled.obj|
MDL_load_main |/home/sroot/Documenti/blend_files/export/untitled.obj| !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
UI_PRI_unl AP_stat.fVwr = 0
GL_selTab_init 0
Brw_init__ 2
 ex-AP_impTyp_get 1
MDL_load_noNat |/home/sroot/Documenti/blend_files/export/untitled.obj|_home_sroot_Documenti_blend_files_export_untitled_obj|
   _load_noNat-1 |_home_sroot_Documenti_blend_files_export_untitled_imp_obj|_home_sroot_Documenti_blend_files_export_untitled_imp_obj|
ex-MDL_load_noNat 0 symNam=|_home_sroot_Documenti_blend_files_export_untitled_imp_obj|_home_sroot_Documenti_blend_files_export_untitled_imp_obj|
MDL_load_import__ 13 |/home/sroot/Documenti/blend_files/export/untitled.obj|
 ex-AP_impTyp_get 1
::::UTF_alloc__ 485 2000000 0
Brw_init__ 2
Brw_Prcs_Init 
AP_Init2 1
MDL_load_import__ 13 |/home/sroot/Documenti/blend_files/export/untitled.obj|
 ex-AP_impTyp_get 1
AP_kex_exec |xa_obj_r|gCad_main| mode=16
 DLL_LOAD_only |/usr/lib/gcad3d/Linux_x86_64//xa_obj_r.so|
 DLL_CONNECT  |gCad_main|
gCad_main-xa_obj_ut.c
ex-plugin-obj-imp 0
 ex-AP_kex_exec 0
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

Greetings

**Comment by gcad3d** [comment]
Hallo,
- crash only for only for obj-models, native models OK ? Stepmodels OK ?
Did you use the precompiled version from gcad3d.org or did you build yourself ?
The debugger is off for the precompiled version ..
Franz

**Comment by pafurijaz** [comment]
STEP models are fine, the problem only happens with OBJ files, only if I interact with them in the window, until I click on them everything is OK, I can also export.

I downloaded the deb file from the site, I didn't compile it, but I can try to do it, I don't remember all the steps but I compiled it a few times in the past.
So, now for a better debug, I've to compile by self?, This will require a while.

Greetings.

**Comment by pafurijaz** [comment]
Hi Franz, here an other issues that I don't understand, file as VRML 1 and 2 Saved with gCAD3D are impossible to open again with it while other application can import them without issues, but seem that isn't a supported format, I think in the previous gCAD3D was possible, or I'm wrong?

**Comment by gcad3d** [comment]
I could provide a version with debug=ON; maybe this would help to solve the
problem ?
For our big goal - the boolean operatons with bodies - many changes are
necessary, and it will still take a long time. Not all export - import - modules
are always up to date ..
- not enough people for this project.
Greetings

**Comment by pafurijaz** [comment]
Of course it would be fine if you provide me with an executable version without installing from the directory, I understand that there aren't enough people, when you have time it would certainly be useful to understand what the problem could be.

Greetings

**Comment by gcad3d** [comment]
have placed a minimal version with obj input at:
gcad3d.org/download/gcad_deb_V2_60_06.zip
Hope this helps to find the problem ..
Greetings

**Comment by pafurijaz** [comment]
Thanks I will do some test. :)

**Comment by gcad3d** [comment]
Have modified gCAD3D_gui_gtk2.so (func GUI_popup_cb2 modif. and testoutput). 
Please replace this file and test. 
Thanks for you help and greetings.

**Comment by pafurijaz** [comment]
Hi Franz I will try to re download again.
Soon I answer again.
Greetings

**Comment by pafurijaz** [comment]
Hi again, now the output is much less here the error:

```
Thread 1 "gCAD3D" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737326066176) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: File o directory non esistente.

```
Greetings

**Comment by gcad3d** [comment]
at the moment no idea what to do ..
gcad does not use threads; so it must be in gtk2 or gl ..
- and native files and dxf-import-files are OK ?

**Comment by pafurijaz** [comment]
Hi Franz, it's only the OBJ file, which creates problems for me, I can interact and save all the others, I often use it to save DXF files from other files and to export to IGES, I try to understand what I can depend on, maybe I'll also try to compile gCAD3D myself, if I understand I will inform you.

Greetings

**Comment by gcad3d** [comment]
So: other plugins (xa*.so - files) seem to work ok (eg xa_dxf_r.so xa_ige_w.so).
That means the problem is in xa_obj_r.so.
I will check it and provide a debug-version of it.
Greetings.

**Comment by gcad3d** [comment]
Have updated teh debug-file; please see README.debug.
Greetings from Vienna.

**Comment by pafurijaz** [comment]
Hi Franz, seem to me the same that I've already reported with latest one however here, the full console output from the import.

```
MDL_load_noNat |/home/sroot/Documenti/CAD/boat/wrl/Viko_20_V_new.obj|_home_sroot_Documenti_CAD_boat_wrl_Viko_20_V_new_obj|
   _load_noNat-1 |_home_sroot_Documenti_CAD_boat_wrl_Viko_20_V_new_imp_obj|_home_sroot_Documenti_CAD_boat_wrl_Viko_20_V_new_imp_obj|
[Detaching after vfork from child process 176018]
ex-MDL_load_noNat 0 symNam=|_home_sroot_Documenti_CAD_boat_wrl_Viko_20_V_new_imp_obj|_home_sroot_Documenti_CAD_boat_wrl_Viko_20_V_new_imp_obj|
MDL_load_import__ 13 |/home/sroot/Documenti/CAD/boat/wrl/Viko_20_V_new.obj|
 ex-AP_impTyp_get 1
::::UTF_alloc__ 484 2000000 0
Brw_init__ 2
Brw_Prcs_Init 
AP_Init2 1
MDL_load_import__ 13 |/home/sroot/Documenti/CAD/boat/wrl/Viko_20_V_new.obj|
 ex-AP_impTyp_get 1
AP_kex_exec |xa_obj_r|gCad_main| mode=16
 DLL_LOAD_only |/usr/lib/gcad3d/Linux_x86_64/xa_obj_r.so|
 DLL_CONNECT  |gCad_main|
gCad_main-xa_obj_ut.c
ex-plugin-obj-imp 0
 ex-AP_kex_exec 0
UI_viewCB |ResView|
GUI_popup_cb2 ev=7
*** stack smashing detected ***: terminated

Thread 1 "gCAD3D" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737326066176) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: File o directory non esistente.
```

Greetings

**Comment by gcad3d** [comment]
the 1. parameter (parent) of GUI_popup_cb2 seems to be KO.
Until now we cannot find any vialation of the stack; valgrind cannot help.
After import of obj; can you save the model - and later load ?
What if you import obj, immediately export as dxf.
Has dxf been written - can you load it ?
Hard to find the problem if we cannot reproduce ..
Greetings

**Comment by pafurijaz** [comment]
Hi Franz, I understand the difficulties, and regarding the problem with OBJ, if I save the files in DXF, there are no problems, but if I open these files and click on them, the same thing happens as with OBJ files, I am attaching a series of files created in this period if they can be useful, perhaps it is possible that with these you can reproduce the problem, otherwise leave it, and hope that things will be resolved in the future, when you have sorted out the work you are doing now .
[Testing_file.zip](https://github.com/user-attachments/files/16233323/Testing_file.zip)

Greetings

**Comment by gcad3d** [comment]
since we cannot reproduce the problem on all available Desktops and Laptops, 
- (TODO: watch address of parameter parent of GUI_popup_cb2 with gtk2) -
- we must wait for a chance to do this, sorry for that.
Maybe the change from gtk2 to gtk4 can help,
 but there is also no date yet for a change from gtk2 to gtk4 -
 (gtk3 does not support Legacy-OpenGL, gtk4 does).
We yet hope that one of the community will help ..
Greetings

**Comment by pafurijaz** [comment]
OK Franz, don't worry about that, for now and until a new updated, I will avoid on clicking over OBJ files and thanks for your time.
Greetings.

**Comment by gcad3d** [comment]
Hallo, we fixed a bug causing a crash before activating the GUI with V2_60_06-2. Hope this caused your problem ..

**Comment by pafurijaz** [comment]
Yes, great, it works now, sorry it took me a while to respond but I was in Stuttgart and couldn't try, so I'm closing this Bug report for now.
