### ISSUE TITLE
Statement is overflowing a buffer

### ISSUE THREAD

**Issue by awissu** [gcad3d/gcad3d#8]
Hi!
I bumped into rpmlint erros when building rpm in OBS:
```
[  251s] I: Statement is overflowing a buffer
[  251s] E: gcad3d bufferoverflow /usr/include/bits/string3.h:109
```
Build with flags:  -O2 -g -m32 -march=i586 -mtune=i686 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables

**Comment by gcad3d** [comment]
Hi,
thanks for your effort;
we could fix all warnings in the latest version but:

[  251s] I: Statement is overflowing a buffer
[  251s] E: gcad3d bufferoverflow /usr/include/bits/string3.h:109

how did this happen ? Can we reproduce this ?
How do you "building rpm in OBS: " ?
Franz

**Comment by awissu** [comment]
Here spec file:
https://build.opensuse.org/package/show/home:awissu:branches:science/gcad3d
Here logfile:
https://build.opensuse.org/public/build/home:awissu:branches:science/openSUSE_Tumbleweed/x86_64/gcad3d/_log
```
[  210s] I: Statement might potentially overflow a destination buffer, where a size larger
[  210s]     than the actual buffer was specified
[  210s] E: gcad3d destbufferoverflow ../db/ut_DB.c:1025:3
```

**Comment by gcad3d** [comment]
All serious bugs are fixed, thanks.
After all tests in about a week the new version goes into the repository; then i will close this issue.

**Comment by gcad3d** [comment]
The updated version is online, all bugs fixed.
